name: 'test-report'
on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: ['project-test']
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: JEST Tests
          path: '*.xml'
          reporter: jest-junit
