name: 'Test and Report'

on:
  push:
    branches: [ main, dev ]
  workflow_run:
    workflows: ['commit-validate']
    types:
      - completed
jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Tests and Generate Report
        run: |
          npm run test:report
          mv reports/jest-junit.xml $GITHUB_WORKSPACE/test-results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: $GITHUB_WORKSPACE/test-results.xml

      - name: Notify Test Reporter
        if: always()
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results.xml
          name: JEST Tests
          reporter: jest-junit
